In [28]:
#### import numpy as np
M = np.identity(8);
M;
a = [0,0,0,0,0,0,0,0];

c_p4 = [1, 1, 1, 1, 0, 0, 0, 0];
c_p3 = [1, 0, 0, 0, 1, 1, 1, 0];
c_p2 = [0, 1, 1, 0, 1, 1, 0, 1];
c_p1 = [0, 1, 0, 1, 1, 0, 1, 1];

M = np.insert(M, 4, c_p4, axis=1);
M = np.insert(M, 8, c_p3, axis=1);
M = np.insert(M, 10, c_p2, axis=1);
M = np.insert(M, 11, c_p1, axis=1);
M

array([[1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]])

In [59]:
a = np.zeros((4,4));
b = 4;

a[b//4][b%4] = 5;
a
#1 = pos(1)+4,4,4
#2 = pos(2)+4,4,4
#4 = pos(4)+1,1,1
#8 = pos(8)+1,1,1

array([[0., 0., 0., 0.],
       [5., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [198]:
k = 8;
n = 12;
r = n-k;
parity = np.ones(n-k).astype(int);
parity[0] = 1;
for x in range(1,len(parity)):
    parity[x] = 2*parity[x-1];

vector = np.ones(n);
check_bit = np.full((r,n),0, int);
for j in range(len(parity)):
    for i in range(int(parity[j]), int(parity[j])*2):
        check_bit[j][i-1::2*int(parity[j])] = 1;
#Ahora quitamos del check bit las columnas que se corresponden con valores de paridad
indexes = [];
for x in range(len(parity)):
    indexes = np.append(indexes, int(parity[x])-1);
indexes = indexes.astype(int);

check_bit = np.delete(check_bit, indexes, axis=1);  
check_bit = np.flip(check_bit).T;
check_bit = np.flip(check_bit, axis = 1);
#Las columnas de paridad quedan así
print("columnas de paridad\n", check_bit);

M = np.identity(k).astype(int);
for i in range(len(parity)):
    pos = len(M[0])-(int(parity[i])-1);
    M = np.insert(M, pos, check_bit[:,i], axis=1);
print("forma final de M\n", M);

columnas de paridad
 [[0 0 1 1]
 [1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [1 1 0 0]]
forma final de M
 [[1 0 0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 1 1]
 [0 0 1 0 1 0 0 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 1 1]]


In [11]:
k = 8;
n = 12;
r = n-k;
parity = np.ones(n-k).astype(int);
parity[0] = 1;
for x in range(1,len(parity)):
    parity[x] = 2*parity[x-1];

#Creamos check_bit, una especie de máscara que nos dirá para cada bit de paridad, que elementos de X debemos observar
check_bit = np.full((r,n),0, int);
for j in range(len(parity)):
    for i in range(parity[j], parity[j]*2):
        check_bit[j][i-1::2*parity[j]] = 1;
#Ahora quitamos del check bit las columnas que se corresponden con valores de paridad (identidad)
indexes = [];
for x in range(len(parity)):
    indexes = np.append(indexes, parity[x]-1);
indexes = indexes.astype(int);

#Eliminamos dichas columnas y volteamos la matriz para que quede con los bits menos significativos al final
check_bit = np.delete(check_bit, indexes, axis=1);  
check_bit = np.flip(check_bit).T;
check_bit = np.flip(check_bit, axis = 1);
#Las columnas de paridad quedan así
print("columnas de paridad\n", check_bit);

M = np.identity(k).astype(int);
for i in range(len(parity)):
    pos = len(M[0])-(parity[i]-1);
    M = np.insert(M, pos, check_bit[:,i], axis=1);
print(M);

columnas de paridad
 [[0 0 1 1]
 [1 1 0 1]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 1 0]
 [0 1 1 0]
 [1 0 1 0]
 [1 1 0 0]]
[[1 0 0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 1 1]
 [0 0 1 0 1 0 0 0 0 0 1 0]
 [0 0 0 1 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 1 0 1 1]
 [0 0 0 0 0 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 1 0 0 1]
 [0 0 0 0 0 0 0 0 0 1 1 1]]


In [10]:
import numpy as np
n = 7;
k =4;
r = n - k;
n_fil = n;
parity = np.ones(r).astype(int);
parity[0] = 1;
for x in range(1,len(parity)):
    parity[x] = 2*parity[x-1];

#Creamos la matriz con las filas y columnas traspuestas para rellenarla por filas
H = np.full((r, n_fil), 0, int);
for i in range (r):
    for j in range (parity[i]):   
        H[i][j::parity[i]*2] = 1; 
H = np.flip(H, axis = 0);
print(H.T);

[[1 1 1]
 [1 1 0]
 [1 0 1]
 [1 0 0]
 [0 1 1]
 [0 1 0]
 [0 0 1]]


In [27]:
import numpy as np
n = 12;
k = 8;
r = n - k;
n_fil = n;
parity = np.ones(r).astype(int);
parity[0] = 1;
for x in range(1,len(parity)):
    parity[x] = 2*parity[x-1];

#Creamos la matriz con las filas y columnas traspuestas para rellenarla por filas
H = np.full((r, n_fil), 0, int);
for i in range (r):
    for j in range (parity[i]-1,parity[i]*2-1):  
        H[i][j::parity[i]*2] = 1; 
H = np.flip(H);
#La trasponemos para tener la matriz H
H = H.T;
print(H)


[[1 1 1 1 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 1 1 1 0 0 0]
 [0 1 1 0 0 1 1 0 0 1 1 0]
 [0 1 0 1 0 1 0 1 0 1 0 1]]
[[1 1 0 0]
 [1 0 1 1]
 [1 0 1 0]
 [1 0 0 1]
 [1 0 0 0]
 [0 1 1 1]
 [0 1 1 0]
 [0 1 0 1]
 [0 1 0 0]
 [0 0 1 1]
 [0 0 1 0]
 [0 0 0 1]]
