
# 1. La biblioteca Numpy: Instalación

Numpy es una biblioteca para Python, orientada al cálculo científico. En nuestro caso, la utilizaremos para representar arrays, tipos de datos básicos y realizar operaciones numéricas simples necesarias para las prácticas.

Si no se tiene la biblioteca instalada, se puede instalar con el gestor de paquetes __pip3__ para Python 3 usando la siguiente orden por línea de comandos:

__pip3 install numpy__

o bien con __Conda__, si esta es la distribución que tiene instalada el estudiante:

__conda install --yes numpy__


__*NOTA: Durante los cuadernos guiados de la práctica usaremos pip3 como gestor principal. Si no lo tiene instalado y usa Ubuntu, puede instalarlo con el comando apt de la siguiente forma:*__

__sudo apt install python3-pip__


Si tiene instalado pip3, puede instalar también NumPy ejecutando la celda de código siguiente:


In [1]:

# OJO!!!! IMPORTANTE!!!!!

# No ejecutar esta celda salvo si se desea instalar NumPy. 
# Si ya lo tiene instalado, comente la siguiente línea con el caracter # :

!pip3 install numpy



# 2. Numpy: Primeros pasos



Para poder hacer uso de NumPy en Python, es necesario importar la biblioteca. Una forma común de hacerlo dentro de un script Python es la siguiente:


In [2]:

# Imports para Numpy
import numpy as np




## 2.1. Introducción a los Arrays en Numpy


Un array NumPy es realmente una malla (matriz, volumen, etc.) de valores del mismo tipo, que se encuentra indexada por una tupla de enteros no negativos. El número de dimensiones de un array es el rango de la malla; Su forma (shape), una tupla de enteros indicando el tamaño concreto de cada dimensión.

Es posible inicializar arrays NumPy desde listas de Python anidadas, y acceder a las celdas usando corchetes. También es posible especificar el tipo de dato de las componentes del array, y acceder a propiedades de un ndarray como:

 - el número total de componentes que existen (campo __size__), 
 - la forma o tamaño en cada dimensión del array (campo __shape__),
 - número de dimensiones (campo __ndim__),
 - tipo de dato de cada componente (campo __dtype__),
 - o el número de bytes que ocupa cada componente (campo __itemsize__), entre otros.



Por ejemplo, la siguiente celda crea varios arrays partiendo de listas Python, imprime el tipo de la variable creada (un array), su forma, y algunas de sus componentes:



In [3]:

# Creación de un array de dimensión/rango 1D con shape (tamaño) 3:
a = np.array([1, 2, 3]) 

# Imprime el tipo del array
print('Tipo de a: ', type(a))

# Imprime el tipo de las componentes del array
print('Tipo de las componentes de a: ', a.dtype)

# Imprime el rango/dimensión del array
print('Dimensiones de a: ', a.ndim)




# Imprime el tamaño del array (3 componentes)
print('Forma de a:',  a.shape)

# Imprime las componentes 0, 1 y 2 del array.
print('Componentes 0, 1, 2 de a: ', a[0], a[1], a[2])


# Asigna el valor 5 a la primera componente del array
a[0] = 5

# Muestra el contenido del array
print('a tras asignar a[0]=5: ', a)



# Crea un nuevo array de dimensión/rango 2, con shape (tamaño 2x3) y con tipo de componentes float
#  desde listas Python anidadas
b = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
print ('Array b: ', b)
      
# Muestra (2,3), 2 filas y 3 columnas 
print('Forma de b: ', b.shape)


# Imprime el rango/dimensión del array
print('Dimensiones de b: ', b.ndim)

# Imprime el tipo de las componentes del array
print('Tipo de las componentes de b: ', b.dtype)




# El acceso a componentes se puede hacer separado por comas, o bien por corchetes separados (al estilo C)
# Muestra algunas componentes: Valores 1, 2, 4.
print('Acceso a componentes de b separado por comas: ', b[0, 0], b[0, 1], b[1, 0])
print('acceso a componentes de b como array de arrays: ', b[0][0], b[0][1], b[1][0])



Tipo de a:  <class 'numpy.ndarray'>
Tipo de las componentes de a:  int64
Dimensiones de a:  1
Forma de a: (3,)
Componentes 0, 1, 2 de a:  1 2 3
a tras asignar a[0]=5:  [5 2 3]
Array b:  [[1. 2. 3.]
 [4. 5. 6.]]
Forma de b:  (2, 3)
Dimensiones de b:  2
Tipo de las componentes de b:  float32
Acceso a componentes de b separado por comas:  1.0 2.0 4.0
acceso a componentes de b como array de arrays:  1.0 2.0 4.0



También se puede modificar la forma de un array, mediante el método __reshape__, de modo que los mismos datos ocupados por el array tengan una *vista* diferente.

Ejemplo sobre el array de 2x3 de la celda anterior:
 

In [4]:

# Mostramos array inicial
b = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
print(' Array b: ', b)


print('Forma inicial del array: ', b.shape)

# Modificamos a array 1D
b= b.reshape(1,6)

# Mostramos el modificado
print('b con forma (1,6): ', b.shape, b)



# Cambiamos ahora a array de 3x2:
b= b.reshape(2,3)

# Mostramos el modificado
print('b con forma (2,3): ', b.shape, b)



 Array b:  [[1. 2. 3.]
 [4. 5. 6.]]
Forma inicial del array:  (2, 3)
b con forma (1,6):  (1, 6) [[1. 2. 3. 4. 5. 6.]]
b con forma (2,3):  (2, 3) [[1. 2. 3.]
 [4. 5. 6.]]



## 2.2. Funciones adicionales para creación de arrays

Hay funciones básicas que permiten crear arrays con valores predeterminados, como por ejemplo:

 - __np.zeros(tupla)__: Crea un array de dimensión el tamaño de la tupla, y de forma indicada en la tupla, con todas las componentes inicializadas a 0.
 - __np.ones(tupla)__: Crea un array de dimensión el tamaño de la tupla, y de forma indicada en la tupla, con todas las componentes inicializadas a 1.
 - __np.full(tupla, valor)__: Crea un array de dimensión el tamaño de la tupla, y de forma indicada en la tupla, con todas las componentes inicializadas a valor.
 - __np.eye(valor)__: Crea una matriz identidad cuadrada de dimensión valorxvalor.
 - __np.random.random(tupla)__: Crea un array de dimensión el tamaño de la tupla, y de forma indicada en la tupla, con valores aleatorios.
 - __np.arange(inicio, final, paso)__: Crea un array desde inicio hasta final (no inclusive), tomando valores de paso en paso.
 - __np.linspace( min, max, tam )__: Crea un array de tam números distribuidos uniformemente entre min y max

In [5]:

# Array de elementos de 0 a 30 (no inclusive), de 2 en 2
a= np.arange(0, 30, 2)
print('Array del 0 al 30 (no inclusive), de 2 en 2: ', a)


# Ejemplo: Crear matriz de ceros de 2x3
a = np.zeros((2,3))
print(' Matriz de ceros de 2x3: ', a)


# Ejemplo: Crear matriz de unos de 2x3x4
a = np.ones((2,3,4))
print('Array (2,3,4): ', a)


# Ejemplo: Crear matriz de 7's de 4x3
a = np.full((4,3), 7)
print('Matriz de 4x3 inicializada a 7: ', a)



# Ejemplo: Crear matriz identidad de 5x5
a = np.eye(5)
print('Matriz identidad de 5x5: ', a)


# Ejemplo: Crear matriz aleatoria de 5x3
a = np.random.random((5,3))
print('Matriz aleatoria de 5x3 aleatoria en [0,1]: ', a)

# Ejemplo: Crear array con linspace
a= np.linspace(0,2,9)
print('Array creado con linspace: ', a)

Array del 0 al 30 (no inclusive), de 2 en 2:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
 Matriz de ceros de 2x3:  [[0. 0. 0.]
 [0. 0. 0.]]
Array (2,3,4):  [[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
Matriz de 4x3 inicializada a 7:  [[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
Matriz identidad de 5x5:  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Matriz aleatoria de 5x3 aleatoria en [0,1]:  [[0.99534099 0.39720571 0.73740688]
 [0.25012791 0.00813794 0.53846465]
 [0.91215185 0.0677487  0.32765427]
 [0.55452249 0.63996488 0.42173882]
 [0.99186473 0.83743283 0.60870476]]
Array creado con linspace:  [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]



## 2.3. Indexación avanzada

Ya hemos visto que se puede indexar un array por valores separados por comas, o usando la notación de array de array. Existen otras formas que a veces simplifican el acceso a datos, principalmente por rangos:


In [6]:

# Creación de array de 3x4
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('Array a: ', a)

# Acceso básico separado por comas
print('Acceso a a[1,2] separado por comas: ', a[1, 2] ) # Imprime 7

# Acceso básico como array de array
print('Acceso a a[1][2] como array de arrays: ', a[1][2] ) # Imprime 7

# Acceso a componente por tupla 
t=(1,2)
print('Acceso a a[(1,2)] como tupla: ', a[t] )   # Imprime 7


# Acceso por rango: Submatriz de 0 a 1, y de 1 a 2
# OJO!!!: El último valor del rango no está incluido
b = a[:2, 1:3]
print('Acceso a a[:2, 1:3]: ', b) # Imprime la submatriz [[2, 3] ,  [6, 7]]

b = a[1:, :] # Selecciona de la fila 1 en adelante, todas las columnas
print('Acceso a a[1:, :]: ', b) # Imprime la submatriz [[5, 6, 7, 8], [9, 10, 11, 12]]




# Indexación por lista. Crea array con los elementos de las posiciones [0,1] y [1,2]
b= a[[0, 1], [1, 2]]

print('Acceso a a[[0, 1], [1, 2]]: ', b) # Muestra 2 y 7, los elementos que hay en a[0,1] y a[1,2]

# La indexación por lista se puede generalizar a arrays:
filas= [0,1,0]
columnas= [1,2,3]
b= a[filas, columnas] # Array con la selección de los elementos de a en (0,1), (1,2), (0,3)
print('Acceso a a[vector_filas, vector_columnas]: ', b)



# Indexación booleana
a = np.array([[1,2], [3, 4], [5, 6]])
print('Array a: ', a)

bool_idx = (a > 2) # Selección sólo de los elementos de a que son >2
print('Componentes de a>2 como bool: ', bool_idx)

b= a[bool_idx] # Selección booleana
print('Indexación booleana a[bool_idx]: ', b)


Array a:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Acceso a a[1,2] separado por comas:  7
Acceso a a[1][2] como array de arrays:  7
Acceso a a[(1,2)] como tupla:  7
Acceso a a[:2, 1:3]:  [[2 3]
 [6 7]]
Acceso a a[1:, :]:  [[ 5  6  7  8]
 [ 9 10 11 12]]
Acceso a a[[0, 1], [1, 2]]:  [2 7]
Acceso a a[vector_filas, vector_columnas]:  [2 7 4]
Array a:  [[1 2]
 [3 4]
 [5 6]]
Componentes de a>2 como bool:  [[False False]
 [ True  True]
 [ True  True]]
Indexación booleana a[bool_idx]:  [3 4 5 6]



## 2.4. Operaciones aritméticas con arrays

Las operaciones aritméticas sobre arrays se realizan __elemento a elemento__ . Así, el operador + suma elemento a elemento, el operator * multiplica elemento a elemento, etc. . Si se desea realizar operaciones matriciales (por ejemplo, multiplicación de matrices), se deben realizar haciendo uso de operadores específicos para ello (por ejemplo, la función dot ).

Algunos ejemplos:



In [7]:


# Creación de 2 arrays de ejemplo
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Suma de arrays: Por operador y por función
print(' Suma x+y: ', x + y)
print(' Suma np.add(x,y): ', np.add(x, y))
print()

# Multiplicación elemento a elemento
print('Multiplicación x * y: ', x*y)
print('Multiplicación np.multiply(x, y): ', np.multiply(x, y))

# División real
print('División real x/y: ', x/y)
print('División real np.divide(x, y): ', np.divide(x, y))

# División entera
print('División entera x//y: ', x//y)

# Elevar elemento a elemento
print('Elevar elemento a elemento x**y: ', x**y)



 Suma x+y:  [[ 6  8]
 [10 12]]
 Suma np.add(x,y):  [[ 6  8]
 [10 12]]

Multiplicación x * y:  [[ 5 12]
 [21 32]]
Multiplicación np.multiply(x, y):  [[ 5 12]
 [21 32]]
División real x/y:  [[0.2        0.33333333]
 [0.42857143 0.5       ]]
División real np.divide(x, y):  [[0.2        0.33333333]
 [0.42857143 0.5       ]]
División entera x//y:  [[0 0]
 [0 0]]
Elevar elemento a elemento x**y:  [[    1    64]
 [ 2187 65536]]



Además de los operadores aritméticos, NumPy también trae incorporada la funcionalidad de matemáticas básicas (operaciones trigonométricas, exponenciación, logaritmos, etc.).

La lista completa de operadores se puede encontrar en: 

https://docs.scipy.org/doc/numpy/reference/routines.math.html

Algunos ejemplos:


In [8]:

x = np.array([[1,2],[3,4]])
print('Vector x: ', x)

# Prueba de algunas funciones matemáticas
print('Función sqrt: ', np.sqrt(x))

print('Función log2: ', np.log2(x))

print('Función log10: ', np.log10(x))

print('Función exp: ', np.exp(x))

Vector x:  [[1 2]
 [3 4]]
Función sqrt:  [[1.         1.41421356]
 [1.73205081 2.        ]]
Función log2:  [[0.        1.       ]
 [1.5849625 2.       ]]
Función log10:  [[0.         0.30103   ]
 [0.47712125 0.60205999]]
Función exp:  [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]




También trae operadores de agregación sobre matrices/vectores (suma/multiplicación de elementos en un eje, etc.).
Algunos ejemplos:



In [9]:

x= np.arange(15).reshape(3,5)

print('Matriz x: ',x)

y= np.sum(x)
print('Suma de todos los elementos de x: ', y)

y= np.sum(x, axis=0)
print('Suma de todos los elementos de x sobre el eje 0 (filas): ', y)

y= np.sum(x, axis=1)
print('Suma de todos los elementos de x sobre el eje 1 (columnas): ', y)


x= x.reshape(1,15)/np.sum(x)
print('Vector x', x)

y=np.cumsum(x)
print('Suma acumulada de x: ', y)


Matriz x:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Suma de todos los elementos de x:  105
Suma de todos los elementos de x sobre el eje 0 (filas):  [15 18 21 24 27]
Suma de todos los elementos de x sobre el eje 1 (columnas):  [10 35 60]
Vector x [[0.         0.00952381 0.01904762 0.02857143 0.03809524 0.04761905
  0.05714286 0.06666667 0.07619048 0.08571429 0.0952381  0.1047619
  0.11428571 0.12380952 0.13333333]]
Suma acumulada de x:  [0.         0.00952381 0.02857143 0.05714286 0.0952381  0.14285714
 0.2        0.26666667 0.34285714 0.42857143 0.52380952 0.62857143
 0.74285714 0.86666667 1.        ]



## 2.5. Broadcasting

El broadcasting es un mecanismo de NumPy que permite trabajar con arrays de diferente tamaño cuando se realizan operaciones aritméticas.

Algunos ejemplos serían añadir un vector columna a una matriz, o sumar un escalar a un vector, etc.

Ejemplos de broadcasting:


In [10]:

# Definición de array
x= np.arange(15)
print('Vector x inicial: ', x)

# Ejemplo de suma de escalar
y= x+2
print('Suma de escalar 2 a x: ', y)


# Creación de matrices
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(m)   # Creación de matriz y vacía, del mismo tamaño que x
print('Matriz original m: ', m)
print('Vector original v: ', v)

# Ejemplo de añadir vector columna a cada columna de m
for i in range(m.shape[0]): # Recorremos filas
    y[i, :] = m[i, :] + v # A cada fila, se le añade vector
print('Resultado de sumar vector columna con bucle for: ', y)


# Ejemplo de añadir vector columna a cada columna de m, con broadcasting
y= m+v
print('Resultado de sumar vector columna directamente con operador +: ', y)



# Ejemplo de añadir vector fila a cada columna de m con broadcasting
v=np.array([1,2,3,4]).reshape(4,1)
print('Vector fila v= ', v)
y= m+v
print('Resultado de sumar vector columna directamente con operador +: ', y)



# Ejemplo: Cálculo del producto externo
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
print('Vector v=', v, ' y w=', w)
y= np.reshape(v, (3, 1)) * w 
print('Resultado de calcular producto exterior: ', y)


Vector x inicial:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Suma de escalar 2 a x:  [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Matriz original m:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Vector original v:  [1 0 1]
Resultado de sumar vector columna con bucle for:  [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
Resultado de sumar vector columna directamente con operador +:  [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
Vector fila v=  [[1]
 [2]
 [3]
 [4]]
Resultado de sumar vector columna directamente con operador +:  [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]
Vector v= [1 2 3]  y w= [4 5]
Resultado de calcular producto exterior:  [[ 4  5]
 [ 8 10]
 [12 15]]



## 2.6. Operaciones sobre arrays/matrices (no confundir con el tipo matrix)


Numpy también incorpora funcionalidades para operaciones con matrices:

 - Producto matricial (.dot)
 - Traspuesta de una matriz (.T)
 - etc.
 
Ejemplos:


In [11]:


x= np.array([1,2,3]).reshape(3,1)
y= np.array([4,5,6]).reshape(1,3)
print('Array x ', x, ', con shape ', x.shape)
print('Array y ', y, ', con shape ', y.shape)

# Ejemplo de producto
producto= x.dot(y)
print('Producto de matrices: ', producto)


# Ejemplo de trasposición
print('Su traspuesta: ', producto.T)

Array x  [[1]
 [2]
 [3]] , con shape  (3, 1)
Array y  [[4 5 6]] , con shape  (1, 3)
Producto de matrices:  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Su traspuesta:  [[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]



También son muy importantes las operaciones sobre redimensionamiento de arrays, que pueden verse en el siguiente enlace:

https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html

Algunos ejemplos:

 - flatten, que serializa un array a 1D
 - swapaxes, que intercambia 2 ejes de un array

In [12]:

x= np.arange(3*4*5).reshape(3,4,5)
print('Array x: ', x)

# Ejemplo de flatten
print('x flatten: ', x.flatten())

# Ejemplo de swapaxes
y= x.swapaxes(1,2)
print('x swapaxes(1,2): ', y)

# Ejemplo de expandir las dimensiones de un array
y = np.expand_dims(x, axis=-1)
print('Expansión de las dimensiones del array; ', y.shape)


# Ejemplo de eliminar las dimensiones de un array de tamaño 1
y = np.squeeze(y)
print('Eliminar dimensiones de tamaño 1 con squeeze: ', y.shape)

# Slicing de un array 3D
x1,x2,x3= x[0:3]
print('Slice x1: ', x1)


Array x:  [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
x flatten:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
x swapaxes(1,2):  [[[ 0  5 10 15]
  [ 1  6 11 16]
  [ 2  7 12 17]
  [ 3  8 13 18]
  [ 4  9 14 19]]

 [[20 25 30 35]
  [21 26 31 36]
  [22 27 32 37]
  [23 28 33 38]
  [24 29 34 39]]

 [[40 45 50 55]
  [41 46 51 56]
  [42 47 52 57]
  [43 48 53 58]
  [44 49 54 59]]]
Expansión de las dimensiones del array;  (3, 4, 5, 1)
Eliminar dimensiones de tamaño 1 con squeeze:  (3, 4, 5)
Slice x1:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## 2.7. Tipos de datos

Los tipos de datos soportados por NumPy son:

 - np.int8 -> Entero de 8 bits (byte) (-128 to 127)
 - np.int16 -> Entero de 16 bits (-32768 to 32767)
 - np.int32 -> Entero de 32 bits (-2147483648 to 2147483647)
 - np.int64 -> Entero de 64 bits (-9223372036854775808 to 9223372036854775807)
 - np.uint8 -> Entero sin signo de 8 bits (byte) (0 to 255)
 - np.uint16 -> Entero sin signo de 16 bits (0 to 65535)
 - np.uint32 -> Entero sin signo de 32 bits (0 to 4294967295)
 - np.uint64 -> Entero sin signo de 64 bits (0 to 18446744073709551615)
 - np.intp -> Entero de tamaño ssize_t, útil para  indexación (números largos)
 - np.uintp -> Entero largo que puede contener un puntero
 - np.float32 -> Float de precisión simple
 - np.float64 -> Float de doble precisión
 - np.complex64 -> Complejo de 64 bits (32 bits parte real e imaginaria)
 - np.complex128-> Complejo de 128 bits (64 bits parte real e imaginaria)


Se puede especificar y crear nuevos tipos de datos a través de objetos __dtype__ incluyendo, además, qué tipo de codificación interna se desea para el tipo (Big Endian, Little Endian, etc.).

Algunos ejemplos:



In [13]:

# instanciación de un tipo como un dato:
dt = np.dtype(np.int32)
print('Tipo entero de 32 bits: ', dt)


# Creación de un tipo de dato equivalente a "unsigned short", usando Big Endian
dt = np.dtype('>H')
print('Unsigned Short con Big Endian: ', dt)

Tipo entero de 32 bits:  int32
Unsigned Short con Big Endian:  >u2



# 3. Más información:

Se puede visitar las siguientes webs para más información sobre funcionalidades de la biblioteca NumPy:

 - Información avanzada sobre tipos de datos y creación de tipos de datos: https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html
 
 - Información básica sobre Numpy: https://cs231n.github.io/python-numpy-tutorial/
 
 - Información básica complementaria sobre Numpy: https://docs.scipy.org/doc/numpy/user/quickstart.html
 
 - Manipulación de arrays en Numpy: https://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html
 
 - Operaciones matemáticas en Numpy: https://docs.scipy.org/doc/numpy/reference/routines.math.html